name: My Custom CI on Self Host

on:

  schedule:
    - cron: '* * * * *'  # Runs at midnight UTC every day
  push:
    branches: [ "default", "new_branch" ]
  pull_request:
    branches: [ "default" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: echoing
      run: echo "Running hello world from workflow" && gcc HelloWorld.c && ./a.out
